docker/kitematic

meteor/client/lib/boot2docker.js
meteor/client/lib/imageutil.js
meteor/client/views/dashboard/components/modal-create-image.js

Fixes:
- Incorrect detection of Boot2Docker on a new Mac
- Problem where image would not build from a directory with spaces or uppercase characters.

Important setup + image building bug fixes

---

app/ContainerDetails.react.js
app/ContainerModal.react.js
app/ContainerStore.js
app/Containers.react.js
app/styles/container-modal.less
app/styles/main.less
app/styles/theme.less

Also move container styles into container-modal.less

Add tag dropdown for creating containers with a specific image tag

---

src/ContainerListItem.react.js
src/ContainerStore.js
src/Containers.react.js

Fixes:
- Showing `Waiting for another Download` even though it isn't true
- Deleting a downloading container now works

Fix downloading

---

src/Setup.react.js
src/SetupStore.js
src/SetupUtil.js

- Better wording for upgrading VirtualBox. Please review wording @Elesant @mchiang0610 
- Fixes a bug where if VirtualBox was already installed and a boot2docker VM was running the install would fail

Fix upgrading

---

src/MenuTemplate.js

Leads to this page: https://github.com/kitematic/kitematic/issues/new

Basic issue reporting from Help menu

---

src/ContainerDetailsSubheader.react.js
src/ContainerStore.js
src/DockerMachine.js

- Restart now keeps the same port
- Terminal into container no longer depends on active machine

Fix minor bugs

---

LICENSE

Change to Apache license.

---

README.md
ROADMAP.md

Kitematic roadmap update.

---

CONTRIBUTING.md

Update for Apache license to contributing license.

Update for Apache license to contributing license.

---

src/ContainerHomeFolders.react.js
src/ContainerSettingsVolumes.react.js
src/ContainerStore.js

Fixes:
- #209 (volume can now be removed and is off until directory icon is clicked) 
- #256
- #266

Fixes for various volume-related bugs

---

src/ContainerHome.react.js
src/ContainerHomeLogs.react.js
src/ContainerLogs.react.js
src/LogStore.js

This should:
- fix #301 
- fix #288 
- fix #311
Not that we don't cache the logs but limit them to 3000 for now. ContainerLogs.react and ContainerHomeLogs.react still need to be refactored together.

Fixes for log issues

---

gulpfile.js
package.json
src/SetupStore-test.js
src/SetupStore.js
util/deps

- Also removing some bad practices in package.json where the `postinstall` would do some unnecessary dev setup.

Bumping to 0.5.14 with docker 1.6 and docker-machine 0.2.0

---

src/ContainerHome.react.js
src/ContainerStore.js

- New v2 images still have some issues
- Further work required to choose registry v2 by default (right now we chose v1) and then backfall to v1

Fixes progress bar for old v1 images

---

src/ContainerDetailsSubheader.react.js

Fixing incorrect classNames require

---

styles/new-container.less

Fixes issue: https://github.com/kitematic/kitematic/issues/442

Added fix for tag display

---

styles/container-home.less
styles/mixins.less
styles/new-container.less
styles/right-panel.less

Tweaked UI colors (clearer borders)

---

src/components/ContainerDetailsSubheader.react.js

Implemented a simple check for a custom shell assigned by the user within the Global settings.

Added support for env shell called via settings

---

src/stores/ContainerStore.js
src/stores/LogStore.js

Fix live logs

---

src/components/ContainerDetailsSubheader.react.js

This should fix the issue seen at:
https://github.com/kitematic/kitematic/issues/465
Fixes: #465

Fixed stop button showing on initial start

---

CONTRIBUTING.md

Signed-off-by: Sven Dowideit <SvenDowideit@docker.com>

One more thing that kitematic helps with

---

docs/rethinkdb-dev-database.md
docs/userguide.md

Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

replace PID-0 with main container process, and tweak a little

---

src/components/ContainerProgress.react.js
styles/container-progress.less
styles/main.less

Usage: `<ContainerProgress pBar1={20} pBar2={70} pBar3={100} pBar4={20} />`

Added Container Progress component

---

src/components/ContainerHome.react.js
src/stores/ContainerStore.js
src/utils/DockerUtil.js

Improved pull image loading

---

src/components/ContainerHome.react.js
src/components/ContainerProgress.react.js
src/utils/DockerUtil.js
styles/container-progress.less
styles/right-panel.less

Aligned image download progress indicator

---

src/components/Header.react.js
src/components/NewContainerSearch.react.js

text case fix - I've verified my email address

text case fix - I've verified my email address

---

src/components/AccountLogin.react.js

Consistent text - username/password

---

src/components/ImageCard.react.js
styles/theme.less

Tweaked positive button.

---

styles/container-home.less
styles/container-settings.less
styles/left-panel.less
styles/variables.less

Added a new gray color.

---

.travis.yml
__integration__/HubUtil-integration.js
__integration__/RegHubUtil-integration.js
__tests__/SetupStore-test.js
__tests__/URLUtil-test.js
__tests__/Util-test.js
__tests__/VirtualBoxUtil-test.js
jest-integration.json
jest-unit.json
package.json

- Run with `npm run integration`
- Code coverage disabled for now so tests work on Windows

Adding integration tests

---

src/actions/ContainerActions.js
src/components/ContainerDetailsSubheader.react.js
src/utils/DockerMachineUtil.js
src/utils/DockerUtil.js

There were some simple warnings associated with the objects passed that were fixed - I also added a patch to the 'Random port issue' https://github.com/kitematic/kitematic/issues/530 
Port mapping settings view will also be updated shortly, as it's referencing the wrong object.

Random port mapping and warnings

---

src/components/ImageCard.react.js
styles/new-container.less

Added informative text for selecting image tags

---

.circle.yml
.gitignore
__integration__/HubUtil-integration.js
__integration__/RegHubUtil-integration.js
src/actions/RepositoryServerActions.js
src/actions/TagServerActions.js
src/stores/TagStore.js
src/utils/HubUtil.js
src/utils/RegHubUtil.js
util/testenv.js

- Adding callbacks to a few `utils` functions so they're testable. In the future we should probably use promises or async

Docker Hub Integration tests

---

src/components/ContainerHomeFolders.react.js
src/utils/Util.js

Ref: https://github.com/kitematic/kitematic/issues/579 (needs testing on windows)

Moved Kitematic dir to Documents

---

src/components/ContainerHomeFolders.react.js
src/components/Containers.react.js
src/stores/SetupStore.js
src/utils/SetupUtil.js
src/utils/VirtualBoxUtil.js
styles/theme.less

- Fixes bug where `/dev/vboxnetctl` is not loaded at setup
- Fixed outline around + button in-app

Setup + Style fixes

---

styles/header.less
styles/theme.less

Fixed auto-update button layout.

---

src/components/Header.react.js
src/components/NewContainerSearch.react.js
styles/header.less
styles/new-container.less

Fixed long username and adjusted verify account layout.

---

src/components/ContainerHome.react.js
src/components/NewContainerSearch.react.js
styles/right-panel.less

More graceful error for pulling and creating containers.

---

styles/left-panel.less
styles/new-container.less
styles/right-panel.less
styles/theme.less
styles/variables.less

Larger font and circular button alignment fix

---

CONTRIBUTING.md

Please read over Windows section for prereqs.

Update contributing guide for Windows dev

---

docs/Dockerfile
docs/index.md
docs/minecraft-server.md
docs/nginx-web-server.md
docs/rethinkdb-dev-database.md
docs/userguide.md

This PR fixes problems found in review yesterday.  Review so you understand, then, do the following:
1. Merge into `master` branch.
2. Cherry-pick merge commit into the branch where you want me to release docs from.
3.  Send me an email with titled *Release Kitematic Docs from BRANCHNAME*
Unfortunately, while I fixed the majority of problems with your content there are a few remaining ones that  we **must address after the release** these are:
- couple # links are not working; confirmed sed scripts not the problem
- couple links to .md files in a repository are not working (.md)

Hugo final 1.7 Documentaiton PR -- please read carefully

---

package.json

Two days ago RC3 of docker-machine has been released. Changes:
https://github.com/docker/machine/releases/tag/v0.3.0-rc3

Upgrade to latest docker-machine RC

---

src/components/ContainerDetailsSubheader.react.js
src/components/ContainerSettings.react.js
src/components/ContainerSettingsAdvanced.react.js
src/components/ContainerSettingsGeneral.react.js
src/components/Containers.react.js
src/routes.js
src/stores/ContainerStore.js
src/utils/RegHubUtil.js
styles/container-settings.less
styles/preferences.less

Design polish TTY and STDIN

---

README.md

Quick update for Windows uninstall

---

README.md

Adding Install Docker Commands with image

Adding Install Docker Commands

---

src/components/ImageCard.react.js

Load recommended images over https

---

docs/userguide.md

I fixed some small typos and grammatical issues. I tried to avoid overly opinionated changes.

Copy edit user guide

---

docs/userguide.md

volume data path should be `~/Documents/Kitematic/<container's name>/`.

Fix volume data path on guide

---

styles/setup.less

Add some simple css to allow text-selection of the VM error when it does occur. 

Added highlight for VM error

---

docs/userguide.md

Added Documents/ to path.  This should close issue https://github.com/kitematic/kitematic/issues/830
Signed-off-by: Christian Clauss cclauss@bluewin.ch

Correct the local directory path in Managing Volumes

---

docs/Dockerfile
docs/faq.md
docs/index.md
docs/pre-process.sh
docs/userguide.md

- Fixes #877 to update the install for toolbox
- Updates to the documentaiton infrasturture now can build entire public projects from kitematic
- Updates to the FAQ to make clear Windows is now supported
Signed-off-by: Mary Anthony <mary@docker.com>

Update installation for Toolbox

---

src/components/AccountLogin.react.js

Bug: Incorrect Reset Password URL

---

docs/userguide.md

Link to machine fix it!
Fixes: https://github.com/docker/docker/issues/15870
Signed-off-by: Mary Anthony <mary@docker.com>
cc: @mchiang0610 @jeffdm @theJetzah

Fixing problem reported by Sabine

---

docs/index.md

(cherry picked from commit b4c71d79d8f8483d2e1f54b21c5a074cc918d22d)

fix mac link

---

src/components/ContainerDetailsSubheader.react.js

Added link to the docs for the specified image within the container window - Allowing for easier lookup of documentation and how-to for that particular container.

Added hub docs link within container

---

src/components/ContainerHomePreview.react.js
src/utils/Util.js

Added new port to the web-preview. Updated some of the spacing/indentations

Added 8888 as webport and fixed indents

---

src/components/ContainerSettingsPorts.react.js
src/utils/ContainerUtil.js
styles/container-settings.less

All of this was based on the great work by @VojtechBartos but it's been updated to match the current code base with the addition of Getting exposed ports and previously set port settings.

Updated support for port edit and improved exposed ports shown

---

src/utils/RegHubUtil.js

This adds support for organization repos - Previously only a user's repo would be shown, not the org he belonged to.

Added support for ORG repos

---

src/routes.js

Improves relative paths for react-router

Improves relative paths for react-router

---

src/stores/AccountStore.js
src/utils/HubUtil.js
src/utils/RegHubUtil.js

Signed-off-by: Jeffrey Morgan <jmorganca@gmail.com>

Use new /logout endpoint

---

docs/Dockerfile
docs/minecraft-server.md
docs/nginx-web-server.md
docs/rethinkdb-dev-database.md
docs/userguide.md

Updates the content for use with Hugo 15 patch. @SvenDowideit created this patch
The patch supports GitHub source relative links
Signed-off-by: Mary Anthony <mary@docker.com>

Updating with Hugo 15

---

src/utils/DockerMachineUtil.js

Updated machine info for docker-machine changes

---

src/actions/RepositoryActions.js
src/components/NewContainerSearch.react.js
src/stores/RepositoryStore.js
src/utils/RegHubUtil.js
styles/new-container.less

Updated search to use the V2 standard (same as hub.docker.com) and added pagination for navigation.
Will probably add the same sorting functionality as found on hub also. (hence the comments)
Signed-off-by: FrenchBen <me+git@frenchben.com>

Added V2 search and pagination

---

src/browser.js

Removed unused/out-dated auto-updater.

removed auto-updater

---

src/components/NewContainerSearch.react.js
src/stores/RepositoryStore.js

Added reset of pagination for new search. Fixes #1151

---

src/components/Header.react.js
src/components/Preferences.react.js
src/components/SelectMachine.react.js
src/routes.js
src/utils/DockerMachineUtil.js
src/utils/SetupUtil.js
src/utils/Util.js

Added selector for VM fixes #1061

---

src/utils/RegHubUtil.js

Allows for up to 1000 org images + user images to be displayed

Added larger set for org and user repo - fixes 1158

---

src/browser.js

Increasing width by 70px to have 3 columns of the AppStore.

Increasing width by 70px to have 3 columns of the AppStore.

---

docs/minecraft-server.md
docs/nginx-web-server.md
docs/rethinkdb-dev-database.md
docs/userguide.md

Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>
please :)

Docs validation checker fixes

---

src/app.js
src/utils/SetupUtil.js

Updated setup check

---

Makefile
docs/Dockerfile
docs/faq.md
docs/index.md
docs/known-issues.md
docs/minecraft-server.md
docs/nginx-web-server.md
docs/rethinkdb-dev-database.md
docs/userguide.md

Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>
@moxiegirl this only moves its location in the menu - do you also want to change the URI to `http://docs.docker.com/toolbox/kitematic/` ?

Move Kitematic into the Docker Toolbox menu

---

src/utils/SetupUtil.js
src/utils/Util.js

cc @dgageot @jeanlaurent @FrenchBen @jeffdm  FYI
Requires: https://github.com/docker/machine/pull/2979
Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

Set 'Setup Halted' event instead of 'Setup Failed' for exit code 3

---

package.json
src/actions/SetupActions.js
src/app.js
src/browser.js
src/components/ContainerHomeFolders.react.js
src/components/ContainerListItem.react.js
src/components/ContainerSettingsVolumes.react.js
src/components/Containers.react.js
src/components/NewContainerSearch.react.js
src/components/Setup.react.js
src/utils/DockerMachineUtil.js
src/utils/DockerUtil.js
src/utils/SetupUtil.js
src/utils/Util.js

Updated some of the socket support along with changes to the event listeners. Unused logic was removed to clean up the code

Better socket support

---

jest-unit.json
src/components/ImageCard.react.js

Signed-off-by: Thomas Florin <thoflo002@gmail.com>

fix for displaying no description on repo containers that had short descriptions

---

src/utils/DockerMachineUtil.js

Updated path to be a consistent array throughout.  Fixes #1591 

Updated path to work properly on linux - Fixes #1591

---

src/components/ContainerHome.react.js
src/utils/SetupUtil.js
src/utils/Util.js

Removed all previously commented out code

Remove localstorage

---

src/utils/DockerUtil.js

Updated default cmd

---

src/menutemplate.js
src/utils/DockerUtil.js

Added view menu refresh option - Fixes #1174 :8ball:

---

src/components/ContainerHome.react.js
src/utils/DockerUtil.js
src/utils/SetupUtil.js
src/utils/Util.js

Updated native check and some simple error fix suggestions.

Improved errors and native logic

---

.travis.yml
__mocks__/request.js
package.json
src/utils/DockerUtil.js
src/utils/SetupUtil.js
src/utils/Util.js

Added support for proper hostname and Windows support within native app - Fixes #1661

Updated hostname and Windows integration

---

src/utils/DockerUtil.js
src/utils/SetupUtil.js
src/utils/Util.js

Getting the proper calls added for windows

Added pipe back in

---

MAINTAINERS

to keep it consistent :smile: (see https://github.com/docker/go-p9p/pull/12)
ping @FrenchBen

Update ben's e-mail address

---

src/components/ContainerSettingsAdvanced.react.js
src/utils/ContainerUtil.js

Signed-off-by: Alexei Yuzhakov <sibprogrammer@gmail.com>

Add ability to run privileged containers (fix #269).

---

src/components/ContainerSettingsPorts.react.js

Signed-off-by: Alexei Yuzhakov <sibprogrammer@gmail.com>

Fix ability to click on link on port mapping page (fix #1700).

---

src/utils/DockerMachineUtil.js

Updated the logic for the container exec - Still not perfect but works better in windows when in native.

Fixed container exec

---

Gruntfile.js

Fixes #1718
Signed-off-by: French Ben <frenchben@docker.com>

Fixed release file for ubuntu as zip instead of deb

---

docs/Dockerfile
docs/Makefile
docs/index.md

Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

Fix validataion error

---

package.json

Resolves issue #1729.
Signed-off-by: Clement Ho <ClemMakesApps@gmail.com>

Change npm script for lint to eslint

---

src/components/ContainerSettingsAdvanced.react.js
src/components/Preferences.react.js
styles/container-settings.less
styles/preferences.less

Signed-off-by: Alexei Yuzhakov <sibprogrammer@gmail.com>

Better way to control checkboxes using labels.

---

package.json

Fixes #1802 by showing more error details to the user
Signed-off-by: French Ben <frenchben@docker.com>

Updated dockerode to the latest

---

src/components/ContainerSettingsPorts.react.js
src/stores/ImageStore.js

Fixed image with no tags and changed wording for ports

---

src/utils/DockerMachineUtil.js

Added missing DOCKER_CERT_PATH env check

---

package.json
src/components/ContainerSettingsVolumes.react.js
src/components/Preferences.react.js
src/components/Setup.react.js
src/stores/ImageStore.js
src/utils/DockerUtil.js
src/utils/RegHubUtil.js
src/utils/SetupUtil.js
src/utils/Util.js

* Removed folder limitation for native apps
* Add some caching to the requests
* Added preference of VM vs Native 
Fixes #1707
this can't be merged until this PR is merged: 
https://github.com/alltherooms/cached-request/pull/12

Folder limit

---

src/components/ContainerHomeIpPortsPreview.react.js
src/components/ContainerHomePreview.react.js
src/components/ContainerHomeWebPreview.react.js

this helps in readability of the `ContainerHomePreview` component.

extract some React components

---

package.json

Bump version to pre 1.13

---

circle.yml

Update to the build on Circle to have proper timeout

Update the circle YAML

---

src/utils/Util.js

Signed-off-by: Massimiliano Giroldi <max.devjs@gmail.com>

Fix keyboard accelerators on Linux

---

circle.yml
package.json
src/utils/HubUtil.js
src/utils/RegHubUtil.js

Applies the `authconfig` patch from `docker-modem` https://github.com/apocas/docker-modem/pull/72

In preparation for 1.13.1 bump the version

---

circle.yml

Caching for the large electron zip downloaded

Add downloaded electron zip to the cache

---

src/components/AccountLogin.react.js

Fixed unmatched parenthesis

---

src/components/ContainerDetailsSubheader.react.js
src/components/Preferences.react.js

Hi @FrenchBen I have re-created the branch with signed commits and made again the pull request;
in according to https://github.com/docker/kitematic/pull/2476#issuecomment-287912797 thread.

Added terminal shell option

---

src/components/ContainerSettings.react.js
src/components/ContainerSettingsPorts.react.js
src/utils/DockerUtil.js
styles/container-settings.less

According to https://github.com/docker/kitematic/issues/2350#issuecomment-287486749 I edited ports tab adding container's hostname configurations:
If not set the current container hostname is loaded.

Added hostname settings to container

---

src/components/AccountLogin.react.js

If the email is correct, then the `else if` would evaluate to false.
Fix it by nesting the email check _only_ if a `@` is detected.

Fix login with email in AccountLogin.react.js

---

src/components/Setup.react.js

Fixed a typo on the Setup Initialization error page.

Fixed a typo

---

src/components/Setup.react.js

This adds a small reset button that will allow a user to reset their local settings, should they run into issues. 
Fixes #2633

Added small reset button for settings

---

src/components/ImageCard.react.js
src/components/NewContainerSearch.react.js
src/utils/DockerUtil.js
styles/new-container.less

Although not a great way to do it, this is a quick fix to prevent dangling images from breaking the local image removal.
Additionally the parsing of local registry images should also be fixe 🎉

Allow images to be removed even if dangling exist

---

src/components/ContainerSettingsNetwork.react.js
src/components/Preferences.react.js
src/utils/ContainerUtil.js
src/utils/DockerUtil.js
styles/theme.less

List linked containers and open container page.
Allow to manage container links adding new or remove an existing existing one. 
Add style to select input.

Added links section to network container tab

---

src/components/Preferences.react.js
src/utils/SetupUtil.js

Updated functionality linked with the VM preference and remove concerns found in https://github.com/docker/kitematic/issues/2338

Updated wording for VM pref and vm selection

---

src/utils/DockerUtil.js

Add tag as a status for refresh to catch locally built images

---

src/components/ContainerHomeLogs.react.js
styles/container-logs.less

**What does this PR do?**
- Adds button for the user to copy container logs to the clipboard.
- Enables user to adjust the font size for logs.
[Fixes issue #3223 ]

3223 Font too small and can't copy log.

---

src/browser.js
src/components/Header.react.js

The fix was tested on Arch Linux but should work on any Linux

Fixed application still running after exit on Linux (#1996)

---

circle.yml
jest-integration.json
package.json

Fixes the following CVE:
* [CVE-2015-9251](https://nvd.nist.gov/vuln/detail/CVE-2015-9251) - Moderate severity
* [CVE-2016-10707](https://nvd.nist.gov/vuln/detail/CVE-2016-10707)  - Moderate severity

Updated jquery as recommended by github

---

styles/container-home.less

[Bug]: No scroll on long logs in "Container logs"

---

src/menutemplate.js

Preferences doesn't open if main window closed

---

src/components/ContainerHomeLogs.react.js

Focus downloaded file in explorer after saving logs for container

---

src/components/ImageCard.react.js
styles/new-container.less

Add an input text to filter tag names in image overlay. Fixes #3781 
Signed-off-by: Gael Hanquez <hanquez.gael@gmail.com>

Add an image tag names filter

---

__tests__/Util-test.js
jest-integration.json
jest-unit.json
package.json

Upgraded jest version to latest: 21.2.1. This required some changes in test config files.

Upgraded jest version

---

Gruntfile.js
package.json

- fix the naming of the archives
- fix the signing of osx package
- increase the version number

Prepare 0.17.5

---

src/utils/DockerUtil.js

4009 Fix can not create container from private image

---

src/components/NewContainerSearch.react.js

Remove pagination if image filter is set to "My Images"
Signed-off-by: Florian Orben <florian.orben@schmetterling.de>

Fixes #3684 - Don't show page bar

---

.travis.yml
package-lock.json
package.json
src/app.js
src/browser.js
src/components/ContainerHomeFolders.react.js
src/components/ContainerHomeLogs.react.js
src/components/ContainerListItem.react.js
src/components/ContainerSettingsGeneral.react.js
src/components/ContainerSettingsVolumes.react.js

DESKTOP-3015: Bump kitematic dependencies

---

package-lock.json
package.json

Attempt to fix CVEs. Not sure if it works.

DESKTOP- 3169: Fix kitematic cve
