docker/kitematic

src/ContainerDetailsSubheader.react.js

Small fix for terminal button open empty terminal when you have a port defined in you ssh client config ('Port xx' in ~/.ssh/config)
see https://github.com/kitematic/kitematic/issues/268

fix issue 268

---

index.html
src/Startup.js

Without such fix, on windows application loads two instances of React at start time, and crashes.
This is connected to the issue #319

A fix required to load only one instance of React in the application. 

---

src/ImageCard.react.js
styles/new-container.less

Altered the repo name on the ImageCard to open the Docker Hub page for the repo when it is clicked on. I tried to follow the style that you all use for the tag link - though I am not sure that is how you want it to be styled (feel free to change to conform to the standards you are trying to set).
A more advanced version of this might be to open that page within another window.

Altering the repo name to be a link that takes you to the Docker Hub page

---

src/ContainerHomePreview.react.js

Removing the reload (and the whole `componentDidMount` function since the reload was the only thing in there) makes sure that the container view isn't reloaded when the DOM changes and so does not make a request to the container. Because of this change kitematic will not make a request to the container when hovering over the preference button.
(I wasn't sure if this was used somewhere for real. If it is, I couldn't find it).
Fixes #333.

Remove `componentDidMount` function with reload.

---

src/ContainerHome.react.js
src/ContainerStore.js

Make sure that errors that happen when pulling image layers bubble up to the UI. We do this by catching errors coming from the docker client, calling the callback with that error and setting the global variable `_error` as the error we just caught. This is to make sure that when the stream ends we call the callback with the error as well as to not to over-ride it.
Finally we remove the hard-coded message in the UI and display the error that gets passed in to it through the props attribute. This is the only part I'm not super sure on if we really want since it must have been set there for a reason. If I can get a re-producible test case I can make sure that it's still passing with this patch.
Fixes #355.
Signed-off-by: Kristján Oddsson <koddsson@gmail.com>

Replace hard-coded error message with props.

---

src/ContainerHome.react.js
src/ImageCard.react.js

Should fix #350 in the sense that the error "No command specified" will bubble up to the UI when trying to start a container that has no `CMD` in the Dockerfile.
I made example usage gifs using the `google/debian` image:
- [before](https://cloud.githubusercontent.com/assets/318208/6997501/d318902e-dbac-11e4-881a-f4610fd5e89a.gif)
- [after](https://cloud.githubusercontent.com/assets/318208/6997500/d2d69782-dbac-11e4-8cb7-a6ab25efc262.gif)
This does not fix the "No logs for this container" when booting containers such as the official ubuntu and debian images since they have `CMD` statements in their Dockerfile.

Update tags on mounting ImageCard component.

---

src/ContainerList.react.js

When a container is first started and the image is downloading there is no id set. With this patch we'll check if the container has a id and and is downloading, if so we'll substitute it with the image name and render such.
This will fix the react key props warning in the developer console as well as maybe give us some sort of performance boost(?)

Fall-back to image name as key when there is no id

---

.gitignore
src/DockerMachine.js
util/deps

- Fixes bug where boot2docker.iso can't be downloaded (due to timeout, GitHub API limit hit, etc.)

Include boot2docker iso in distribution

---

src/ContainerList.react.js
src/Containers.react.js

This re-enables downloading multiple images at once, since the v2 registry fixed the bug where trying to download `redis` or other images twice would break the daemon.

Allow downloading multiple containers

---

package.json
src/alt.js
util/prepare.js
util/preprocessor.js

This makes test output much easier to read by showing the correct lines where tests fail or errors occur.

Adding sourcemaps to tests

---

CONTRIBUTING.md

Need to think about minimum versions, as it upgraded some thing, but not vbox
Signed-off-by: Sven Dowideit <SvenDowideit@docker.com>
does it download and upgrade the docker client too? (I think so, as my older setup suddenly broke)
I suspect we're best off making the default PATH contain the latest - `boot2docker upgrade` is also rude in this way, but perhaps we should warn and confirm that we're about to do something that could break a carefully setup old docker&vm config someone is busy using.

Add info about what the pre-requisites are

---

src/utils/DockerUtil.js

Fixed #603 
Thanks for the help @nathanleclaire.
The API requires that containerData.volumes has the form:
```
{
vol1: {},
vol2: {},
vol3: {},
...
}

Fixed bug with API requests to 1.7 RC2 /containers/create endpoint

---

src/components/ContainerDetailsSubheader.react.js

Hey guys,
i wanted to set custom shell to `bash` instead of `sh` which is default. I set environment `ENV SHELL /bin/bash`, but it was still picking up default option `sh` every time. I have found in code when you trying to check if somebody wants to set custom shell that you are accessing to array like to object, so i have added simple reduce function to make it actually object.
Hopefully everything is ok ;)
Let me know if you have any questions.
Vojta
Signed-off-by: Vojta Bartos <hi@vojtech.me>

Fixing setting up custom shell in container terminal

---

src/stores/ContainerStore.js

Previous logs only updated when the component mounted, this fix allows for logs to be refreshed whenever the actual container is updated, usually triggered by `containerServerActions.updated({container})`
This should fix issue https://github.com/kitematic/kitematic/issues/535

Fixed stale log refresh

---

src/components/ContainerHomeLogs.react.js

After the UI update it seems that the logs didn't properly scroll automatically to the bottom.  This should fix this issue. 

Fixed scrollbottom

---

src/components/ContainerSettingsGeneral.react.js
src/utils/ContainerUtil.js
src/utils/DockerUtil.js

I've been using busybox-like data containers and noticed that for some it was needed to add `docker run -ti` options to have a pseudo-tty allocated to the container otherwise the container wouldn't stay running. 
Since `-i -t` are commonly added together, it was only normal to also support that option. 
Look and feel:

Added support for docker tty stdin options

---

src/actions/ContainerActions.js
src/components/ContainerListItem.react.js
src/stores/ContainerStore.js
src/utils/DockerUtil.js

Tentatively fixes #687
- Don't reload every container's data when a create event occurs
- Upon loading don't relead every container
This should reduce the O(N^2) cost we saw before by fetching _every_ container on every event.
Note: this will still cause some overhead since it calls `/container/inspect` for every `create`, roughly 150ms per create.

Improve performance by hitting the remote api less

---

src/utils/DockerUtil.js

Previous TTY/Stdin settings weren't kept if General/Volumes/Ports were modified and save - This fixes the issue by reading the Container data before the update.

Fixed Tty and Stdin save

---

src/utils/DockerMachineUtil.js

It looks like docker-machine recently changed their iso naming convention from `boot2docker.iso` to `boot2docker-virtualbox.iso` https://github.com/docker/machine/blob/master/drivers/virtualbox/virtualbox.go#L28
Furthermore the actual iso content versioning no-longer identifies itself as `Boot2Docker-v1.766` as it previously did, but rather contains docker version information, such as `Docker v1.7.1`
This patch changes the iso filename and version check accordingly - Furthermore the code was made a bit more flexible by passing the machine name to the methods, with an ES6 default of the machine name returned by the `name()` method.
Signed-off-by: FrenchBen <me@frenchben.com>

URGENT: Fixed iso and version issues

---

docs/faq.md
docs/known-issues.md

- The Markdown links are being processed by the scripts and stripping of the .md
- using <a> tags prevents the processing and they work OOB
Signed-off-by: Mary Anthony <mary@docker.com>

Fixing links here so they work OOB

---

package.json

Reset the docs to the current master.
We need to do this so that I can do changes for 1.9 without polluting the 1.8 material
I have publishes next week for new DTR and Hub is coming up

Reset docs

---

.eslintrc
package.json

In order to keep code clean and future pull request up to standard, I propose to integrate eslint as part of the code. 
The rules can be modified as needed, as they were taken mainly from:
https://github.com/eslint/eslint/blob/master/.eslintrc
Atom.io packages:
* linter
* linter-eslint

Add lint-eslint support

---

src/utils/DockerUtil.js

Updates the DockerUtil restart functionality so that it follows the Start/Stop methods more closely and prevents loss of port mapping

Updated Container restart

---

src/utils/DockerUtil.js

This fixes the issue seen in many daemons such as https://github.com/kitematic/kitematic/issues/746 - By default the docker CLI uses a timeout of 10s before killing the process, Kitematic did not, which caused issues when a container had a cleanup method on shutdown.
This patch adds the same 10seconds wait time before killing the container.

Fixed start/stop issues

---

styles/new-container.less

Somehow we lost the ability to scroll on the New/Search Container page. This adds some overflow magic.

Enabled scrolling on new container

---

src/actions/ContainerServerActions.js
src/components/ContainerDetailsHeader.react.js
src/components/ContainerDetailsSubheader.react.js
src/stores/ContainerStore.js
src/utils/DockerUtil.js

- The docker daemon emits `kill` events when containers are stopped. We can use this to disable the start, restart and exec buttons while the container shuts down.
- Added a 5 second timeout

Add stopping state to fix immediately killing containers

---

src/components/ContainerHomePreview.react.js
src/components/ContainerSettingsPorts.react.js
src/utils/ContainerUtil.js
src/utils/DockerUtil.js
styles/container-home.less

Port types are now displayed on the home preview:
Additionally port types can be modified as needed and are consistent after start/stop/updates:

Added port type support - fixes #344

---

package.json
src/browser.js

Simple command line change to allow the dev tools to be open when the node env is set to development.
Can be started via command line: `npm run start-dev`

Add package option for devTools window on start

---

src/browser.js
src/components/ContainerHomeFolders.react.js
src/components/ContainerSettingsPorts.react.js
src/components/ContainerSettingsVolumes.react.js
src/utils/DockerUtil.js

This fixes some of the port/binding and volume issue previously seen, by cleaning up the API calls to match the format found in remote api v1.22
See:
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#create-a-container

Updated API calls for 1.22 and electron IPC update

---

src/utils/DockerUtil.js

This fixes #1339, and does not incorrectly set CMD to ENTRYPOINT if no CMD directive was specified.

Fix bug where entry point would be repeated if no CMD was specified

---

resources/terminal

The AppleScript bridge changed at some point since 2.1. While marked as
beta, the 2.9 series is the author's recommended version to use.
The two bridges are incompatible, requiring another function and version
checks.

Add support for launching iTerm 2.9+

---

src/components/ContainerHome.react.js

The subject of the sentence `an error` is singular, therefore `seems` should be used instead of `seem`.

Grammar fix, s/seem/seems/

---

src/app.js
src/browser.js
src/utils/ContainerUtil.js
src/utils/DockerUtil.js

Updated the logs logic and event listener cleanup.

Added closing of event listener

---

CONTRIBUTING.md
src/actions/ContainerActions.js
src/actions/ImageActions.js
src/actions/ImageServerActions.js
src/actions/TagActions.js
src/components/ImageCard.react.js
src/components/NewContainerSearch.react.js
src/stores/ImageStore.js
src/stores/TagStore.js
src/utils/DockerUtil.js
styles/new-container.less

This PR adds a new tab to the New Container view, allowing the user to:
* View all local images
* Create from local image (with tag selection)
* Delete local image
Known issues:
* `docker build` currently doesn't trigger an event, an issue was open with the docker team to get this resolved
* All images are deleted, no single-tag image delete currently possible

Local images support!

---

src/browser.js

Introduce a delay and a two-step close windows procedure to allow to receive and execute the order to stop  the machine when Kitematic closes on Windows.

Fix stop the machine on close on Windows

---

Gruntfile.js

Changes to the Gruntfile to allow to create a release version on Windows
P.S. Avoid the execution of shell:sign and shell:zip because on Windows there is no way to execute the sign process to Mac Applications.
Signed-off-by: Alexandre Vazquez <alexandre.vazquez@gmail.com>

Changes to the Gruntfile to allow to create a release version on Windows

---

src/components/ContainerHome.react.js

Common when the tag is unknown, then the error is just text and should be used as such. Fixes #1703
Signed-off-by: French Ben <frenchben@docker.com>

Added error output when error is unknown

---

src/browser.js

Current code uses deprecated API from Electron. We should be using ```app.on('activate', function () {``` instead of ```app.on('activate-with-no-open-windows', function () {```.
This API change was in Electron v0.32.3 (https://github.com/electron/electron/commit/377e7ee3a728b5b8fe67605025fefc98cfd4f9f4) and we are currently using Electron v0.35.4 according to package.json.
I was getting the following deprecation error in the terminal when I hid the Kitematic window behind other applications and brought it back to the front. ```>> (electron) 'activate-with-no-open-windows' event is deprecated. Use 'activate' event instead.```
Signed-off-by: Clement Ho <ClemMakesApps@gmail.com>

Fix electron deprecated activate API

---

package.json

Grunt-electron-installer modules for debian and redhat will not install on windows unless we move them to optionalDependencies in package.json. Grunt file will error on those platforms if the modules fail to install for some other reason than operating system.
Signed-off-by: Ben Harris benhdev@gmail.com

Move deb rhel electron to optionalDependencies

---

src/components/ContainerHomeLogs.react.js

This resolves issue #1713. It was caused by duplicate React keys for dynamic elements, so I replaced the existing keys with the following keys (which shouldn't overlap since we do not allow multiple containers with the same name):
`${ContainerName}-${lineNumber}`
Signed-off-by: Clement Ho <ClemMakesApps@gmail.com>

Fix duplicate react key issue

---

src/components/ContainerSettingsPorts.react.js

This resolves issue #1779.
The redundant `http://` url formatting when the port is updated is forcing the browser to open URLs with multiple `http://` prefixes. 
For example `http://http://localhost:3000`. The browser parses this url and attempts to load `http//localhost:3000` which fails. 
[http://http://google.com](http://http://google.com) does not equal [http://google.com](http://google.com)
Signed-off-by: Clement Ho <ClemMakesApps@gmail.com>

Remove redundant http:// formatting

---

src/utils/DockerUtil.js

Previously only certificates relative to the home folder
were honored, which made using custom storage locations
via MACHINE_STORAGE_PATH for docker machines quite
cumbersome to use.
This helps with the issue #1640.

Honor DOCKER_CERT_PATH environment in nonNativeSetup

---

src/utils/DockerUtil.js
src/utils/SetupUtil.js
src/utils/Util.js

Fixes #1836 
Previous Docker for Windows versions didn't use `localhost` as the endpoint, which required some extra logic. With the latest release it's been fixed and thus allows for common functionality.

Fix windows connection setup and port publish

---

src/utils/DockerMachineUtil.js

Previously vbox log files were only stored beneath the .docker folder
relative to the user's home-directory which potentially resulted in
filenotfound errors.
We now store the vbox log files relative to the MACHINE_STORAGE_PATH
for docker machines, e.g. on windows
with `MACHINE_STORAGE_PATH` set to `C:\dev\docker\machine`
the logs for the `default` vm would be written to
`C:\dev\docker\machine\machines\default\default\Logs\VBox.log`
Signed-off-by: Thomas Darimont <thomas.darimont@gmail.com>

Honor MACHINE_STORAGE_PATH environment for virtualBoxLogs

---

Gruntfile.js

This fixes the lintian linter errors for the debian package so that it can be installed from the .deb package without tripping the linter. You can check that it passes the linting with 
`lintian Kitematic_0.12.1_amd64.deb `. 
I had to resort to overriding most of the linting messages because they were related either to the way electron packager does the packaging or the Kitematic's module dependencies, both of which are out of scope of a localized fix. You can see the 14 error messages with `lintian --display-level=">=important" -o  Kitematic_0.12.1_amd64.deb`. Most have to do with the embedded libraries.
I've left a comment for each override in the first commit and removed them and collapsed the overrides in the second commit to keep everything clean. 
This bit is kind of **important** - …

Electron debian fix

---

src/menutemplate.js

The previous shortcut, `⇧⌘H`, is not conventional on OS X/macOS, so this simply changes the shift modified to alt/option, per the [OS X Human Interface Guidelines][hig]:
[hig]: https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/MenuBarMenus.html#//apple_ref/doc/uid/20000957-CH29-SW3

Change 'Hide Others' OS X/macOS shortcut to conventional ⌥⌘H [minor]

---

.travis.yml
package.json

Fixes #1944
This adds an engines entry to package.json. It's set to 4.1.1 which is the node version used in all electron versions between [0.33.2](https://github.com/electron/electron/releases/tag/v0.33.2) and [0.36.0](https://github.com/electron/electron/releases/tag/v0.36.0) what covers the current ([0.35.4](https://github.com/docker/kitematic/blob/master/package.json#L23)).
--
This actually brings up the question why the tests on travis [run against 4.2.2](https://github.com/docker/kitematic/blob/master/.travis.yml#L5) as that isn't the node version kitematic actually runs on doesn't it?

Add engines entry to package.json

---

Jenkinsfile

The documentation has been migrated to docker/docker.github.io, so I'm removing this Jenkins file that was running docs-related CI and can start breaking the builds.

Remove jenkinsfile used for docs CI

---

src/utils/Util.js

After clicking on the `exec`-Button, a message popped up, stating `The terminal emulator symbolic link doesn\'t exists. Please read the Wiki at https://github.com/docker/kitematic/wiki/Early-Linux-Support.`.
Sadly:
1.  the message gives no indication of the problem.
2.  The link given in the message, points to the wiki-site [Early-Linux-Support](https://github.com/docker/kitematic/wiki/Early-Linux-Support), which is except a link is empty
3.  The Link contains an anchor [#early-linux-support-from-zedtux](https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes#early-linux-support-from-zedtux), which does not exist on the linked  Wiki-Site.
I got my indication out of #1648.
It may also be good to remove the bad links in the message (and) remove the bad wiki-pages.

improve linux terminal link error message

---

package.json
src/utils/DockerMachineUtil.js

I started to build a [Chocolatey package for Kitematic](https://github.com/stefanScherer/choco-kitematic). But installing VirtualBox, docker-machine and then Kitematic through `choco install` doesn't work yet.
The problem is that Kitematic searches the `docker-machine` binary only with the environment variable `DOCKER_TOOLBOX_INSTALL_PATH`. After installing `docker-machine` with `choco install docker-machine` it is in the user's PATH.
So I enhanced the check to find `docker-machine` in the PATH if no such environment variable is set. The environment variable still has priority over the PATH to keep the same behaviour using the Docker Toolbox.
For Linux the `docker-machine` binary also is searched in PATH so it could be put to another place (perhaps someone compiles it from Go sources).

Use which to find docker-machine

---

src/actions/ContainerActions.js
src/actions/NetworkActions.js
src/components/ContainerSettings.react.js
src/components/ContainerSettingsNetwork.react.js
src/components/ImageCard.react.js
src/routes.js
src/stores/NetworkStore.js
src/utils/DockerUtil.js
styles/new-container.less

These PR add 2 features:
1. Saving network settings when container updates.
2. Configuring container network on separate tab in container settings.
Fixes #1249 
Signed-off-by: Vyacheslav Salakhutdinov <megazoll@gmail.com>

Add tab with configuring container networks

---

src/utils/DockerUtil.js

Fixes #2870 
I think this was just a matter of the namespace being `local-library` instead of `local`.
**Note:** gif is a little long but should be good for proof that the change works.

Use local instead of local-library for local images namespace

---

CONTRIBUTING.md

While working through some eslint updates, I noticed the contributor docs were mentioning jshint. This PR updates that doc to mention eslint (the current linting tool).

Update contrib doc to use eslint

---

src/components/AccountLogin.react.js

Possible fix for #3077.
Screenshots:
There's still a validation for usernames between 4 and 30 characters. This PR doesn't change that.

Remove verbage for email and add validation against email

---

src/components/NewContainerSearch.react.js

Currently, if a user has no images (excluding dangling images), they still will see "My Images" on the "My Images" tab. Instead, they should see "Cannot find any local image."
This refactor aims to fix that and more explicitly filter out these dangling images.
Results of `docker images`:
```
maxhelmetag:~/ $ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
<none>              <none>              a0170d112f0c        5 months ago        520MB
<none>              <none>              6a0c8303ccb8        5 months ago        569MB
```
Before:
After:

Refactor local images view to handle dangling images

---

.eslintrc
package.json

I was having a lot of trouble getting eslint to parse all the files in `src`. It seemed to be sad about the `async` keyword and then, after updating eslint, also `import` and `export`. This seems to have made it better.
I also would like to ask if people would be interested in converting the `.eslintrc` from YAML to JSON. I feel like the eslint docs don't really have YAML examples... which, IMO, can make config changes harder.

Update eslint and eslintrc to not get sad when parsing async

---

src/actions/ContainerActions.js
src/actions/ContainerServerActions.js
src/components/ContainerListItem.react.js
src/components/Containers.react.js
src/stores/ContainerStore.js
src/utils/DockerUtil.js
styles/left-panel.less
styles/variables.less

Hi, tried to resolve the issue #3067 ,
Some screenshots: 
**favorite container -**
**favorites containers and hover on container -**
I'm not sure if the code containerActions.js file is right, 
have a problem that i want to save the favorite names in the localstorage any toggle,
Because if the computer shutdown and the app exiting, i want the favorite to be saved before,
Review it and comment me if something can be improved.
Thank you,
- Added favorites feature for containers.
- Fixed side-bar width css, added cursor: pointer to containers.
Signed-off-by: Daniel Amram <danielamram0@gmail.com>

Added favorites feature for containers.

---

src/components/ContainerHomeLogs.react.js
styles/container-logs.less

**[NOW READY FOR REVIEW]**
- PR enables user to save container logs to file system
**_[on save]_**
Closes issue #2645

Add a way to download logs to file system

---

src/actions/ContainerActions.js

Fix for the favorites containers feature.
Initialize the local history array with default an empty array.
Signed-off-by: Daniel Amram <danielamram0@gmail.com>

- Fixed favorites containers initialize.

---

src/components/ContainerHomeLogs.react.js
styles/container-logs.less

PR enables the user to disable or enable following(auto-scroll down) for container logs. Enabled by default but can be disabled on user demand 🙂 .
_[screenshot]_
Closes issue #2611

[Feature] : Way to prevent auto-scroll down in "Container logs"

---

src/utils/DockerUtil.js

[Bug] Starting container (or tweaking settings) in Kitematic deletes `Labels` settings from `docker-compose`

---

styles/left-panel.less

#3693 
Implements fix for action buttons wrapping when image name is too long.

Update ContainerListItem css so action buttons are no longer wrapping

---

styles/container-home.less
styles/right-panel.less

Defining a width for the `.details` and the `.content .left` elements makes the home/settings tabs and the web preview next to the log lines visible and accessible even if there are very long lines in the request log.
Fixes: #3412

Settings accessible on Ubuntu with long log lines

---

src/app.js
src/components/NewContainerSearch.react.js
src/stores/RepositoryStore.js
src/utils/RegHubUtil.js

- Introduce timeout of 5000ms for fetching repository endpoint
information
- Aggregrate failed requests into one error
- Fix usage of async.map
- Fix deprecated usage of Bluebird's promise cancellation
Signed-off-by: Florian Orben <florian.orben@schmetterling.de>

Fixes #4196 - Kitematic hangs upon doing search - "Loading Images"

---

.circleci/config.yml
.travis.yml

`Array.prototype.includes` is only available in Node.js 6.5+, see https://kangax.github.io/compat-table/es2016plus/#node6_5
https://travis-ci.org/docker/kitematic/builds/443616745

ci: test Node.js 6, 8 and 10

---

src/components/Preferences.react.js
src/utils/Util.js

I add a new field in the settings page, which can be used for set the terminal emulator path.
Now the /usr/bin/x-terminal-emulator is not necessary.

Add linux terminal emulator settings option

---

src/utils/DockerUtil.js

Kitematic v0.17.7 upgrade "dockerode" module to 2.5.8,  Brought a new problem: when opts.follow is false, result type changed from IncomingMessage to Buffer @jdrouet   
my os is MacOS

Fix v0.17.7 container log error
